### ISSUE TITLE
[BUG] Crashes after playing 2 hours duration videos.

### ISSUE THREAD

**Issue by muhitrhn** [Ayeven/generic-bot#9]

**Comment by Ayeven** [comment]
It is because of `youtube-dl-exec`, If you want to use it for big audience, you better find other `readable streamable` source to pass through to `@discordjs/voice`. It is not a big priority for me right now, because this is not intended for big audience. I'm still waiting for discordjs/voicelink` or some other similar, package. So until then, you need to find other source to replace `youtube-dl-exec`

**Comment by muhitrhn** [comment]
Any suggestions on how to find a replacement of `youtube-dl-exec`?
